id = "agda"
name = "Agda"
version = "0.0.1"
schema_version = 1
authors = ["Imbriani Paolo <paoloimbrmagi@gmail.com>"]
description = "Agda language support for Zed, powered by the Agda Language Server (ALS)"
repository = "https://github.com/MagiHotline/zed-agda"

[grammars.agda]
repository = "https://github.com/tree-sitter/tree-sitter-agda"
rev = "b9b32fa042c2952a7bfca86847ea325e44ccc897"

[language_servers.als]
name = "Agda Language Server"
languages = ["Agda"]
